Fix a file scoping issue
Git be crazy sometimes, and was giving an error saying:

```
Exit status of command ‘git --git-dir “/Users/jeremymassel/.mobile-secrets/.git” pull’ was 128 instead of 0.
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
```

`chdir`-ing into the right place, then running `git pull` resolves the issue.