Manually bump build n. to start a new deployment
The `complete_code_freeze` lane failed on my end because of this error:

```
/Users/gio/Developer/a8c/wpios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.195.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[0;31;49m[!] Exit status of command 'git push origin release/18.8:release/18.8 --tags' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
remote: This repository moved. Please use the new location:
remote:   git@github.com:wordpress-mobile/WordPress-iOS.git
To github.com:wordpress-mobile/wordpress-ios
   ce978a3267..4251fe5a6a  release/18.8 -> release/18.8
 ! [rejected]              16.6 -> 16.6 (already exists)
error: failed to push some refs to 'github.com:wordpress-mobile/wordpress-ios'
```

I pushed manually, then run the remaining command in the lane: starting
the CI release build.

Unfortunately, I used my shell history completion and didn't realize I
called the lane to trigger a production release, not a beta.

I noticed that only when looking at the releases in GitHub and seeing
`18.8` instead of the expected `18.8.0.0`. By then, a build had already
been submitted to App Store Connect for WordPress, making it necessary
to bump the number here.

See:
https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-iOS/26003/workflows/e1b2ebbd-5345-4e7e-8181-62669b7238b4